<?php
   $imagePreUrl   = "https://moval.techkrate.com/letterhead/";

	 $approveText 	= "This report is issued without prejudice & generated by VIISLA at the sole request of the party & it is to be used by the sole party for the stated purpose only.<br><br>No Standard price list for vehicle valuation, the valuation indicates in the report is our opinion as per the market value of the said vehicle at the time of inspection. The valuation is based as per vehicle condition at the time of inspection/Valuation.";


	 $job->other_images = [];
	 $number = $job->jobdetail->requested_value;
	 $no = floor($number);
   $point = round($number - $no, 2) * 100;
   $hundred = null;
   $digits_1 = strlen($no);
   $i = 0;
   $str = array();
   $words = array('0' => '', '1' => 'One', '2' => 'Two',
    '3' => 'Three', '4' => 'Four', '5' => 'Five', '6' => 'Six',
    '7' => 'Seven', '8' => 'Eight', '9' => 'Nine',
    '10' => 'Ten', '11' => 'Eleven', '12' => 'Twelve',
    '13' => 'Thirteen', '14' => 'Fourteen',
    '15' => 'Fifteen', '16' => 'Sixteen', '17' => 'Seventeen',
    '18' => 'Eighteen', '19' =>'Nineteen', '20' => 'Twenty',
    '30' => 'Thirty', '40' => 'Forty', '50' => 'Fifty',
    '60' => 'Sixty', '70' => 'Seventy',
    '80' => 'Eighty', '90' => 'Ninety');
   $digits = array('', 'Hundred', 'Thousand', 'Lakh', 'Crore');
   while ($i < $digits_1) {
     $divider = ($i == 2) ? 10 : 100;
     $number = floor($no % $divider);
     $no = floor($no / $divider);
     $i += ($divider == 10) ? 1 : 2;
     if ($number) {
        $plural = (($counter = count($str)) && $number > 9) ? 's' : null;
        $hundred = ($counter == 1 && $str[0]) ? ' and ' : null;
        $str [] = ($number < 21) ? $words[$number] .
            " " . $digits[$counter] . $plural . " " . $hundred
            :
            $words[floor($number / 10) * 10]
            . " " . $words[$number % 10] . " "
            . $digits[$counter] . $plural . " " . $hundred;
     } else $str[] = null;
  }
  $str = array_reverse($str);
  $result = implode('', $str);
  $points = ($point) ?
    "And " . $words[$point / 10] . " " .
          $words[$point = $point % 10] : '';

  if($points == ""){
  	$points = "Zero";
  }
  $amountInWords =  $result . "Rupees  " . $points . " Paise";




	//'Odometer','Other','Video'
	$paddingTableCellHalf = "3px";
	$paddingTableCell = "3px";
	$height           					= "860px";
	$height_horizontal          = "250px";


	$refNo		= $job->reference_no_prefix."/".date('Y')."/".$job->job_report_no;
	$date 		= date('d/m/Y');

	$logoImage 		= $imagePreUrl."Letterhead.png";
	$seal 				= $imagePreUrl."Signature.png";
	//$footer_seal 	= $imagePreUrl."Footer_Image.png";
	$footer_seal 	= "";

	if($job->letter_head_img != ""){
		$logoImage 		= $job->letter_head_img;
	}

	if($job->letter_footer_img != ""){
		$footer_seal 		= $job->letter_footer_img;
	}

	if($job->signature_img != ""){
		$seal 				= $job->signature_img;
	}

	$authorized_person_name		= "";
	if($job->authorized_person_name != ""){
		$authorized_person_name		= $job->authorized_person_name;
	}


	$QrImages 		= ["code-qr1.png","code-qr2.png","code-qr3.png","code-qr4.png","code-qr5.png","code-qr6.png","code-qr7.png","code-qr8.png","code-qr9.png","code-qr10.png","code-qr11.png","code-qr12.png","code-qr12.png","code-qr13.png","code-qr14.png"];
	shuffle($QrImages);
	$barcode 			= $imagePreUrl.$QrImages[0];




	$chassisImage 	= "";
	$frontImage 	= "";
	$backImage 		= "";
	$leftImage 		= "";
	$rightImage 	= "";
	$odometerImage 	= "";

	$footerCount = 0;

	foreach ($job->images as $imgObj){
		switch($imgObj->type){
			case "Chassis Number":
				$chassisImage 	= config('app.imageurl')."".$imgObj->name;
			break;

			case "Front View":
				$frontImage 	= config('app.imageurl')."".$imgObj->name;
			break;

			case "Rear View":
				$backImage 	= config('app.imageurl')."".$imgObj->name;
			break;

			case "Left Side":
				$leftImage 	= config('app.imageurl')."".$imgObj->name;
			break;

			case "Right Side":
				$rightImage 	= config('app.imageurl')."".$imgObj->name;
			break;

			case "Odometer":
				$odometerImage 	= config('app.imageurl')."".$imgObj->name;
			break;


		}
	}


	$username				= $job->contact_person->name;

	$inspectionDateTime		= $job->submission_date;
	$inspectionPlace		= $job->inspection_place;

	$amount					= $job->jobdetail->requested_value;
	$amountWords		= $job->jobdetail->requested_value;


	$vehicelOwnerName		= $job->owner_name;
	$regNo					= $job->vehicle_reg_no;
	$address				= $job->address;
	$vClass					= $job->vehicle_class;
	$dateOfRegistration		= date("d/m/Y",strtotime($job->registration_date));

	$bodyType 				= $job->type_of_body;
	$mfgYear 				= $job->manufactoring_year;



	$additionalKeyValue = array(
		  (object) [
		    'key1' => 'Vehicle Class',
		    'value1' => $job->jobdetail->vehicle_class,
		    'key2' => 'Date Of Registration',
		    'value2' => date("d/m/Y",strtotime($job->jobdetail->registration_date)),
		  ],
		  (object) [
		    'key1' => 'Type Of Body',
		    'value1' => $job->jobdetail->type_of_body,
		    'key2' => 'Manufacturing Year',
		    'value2' => $job->jobdetail->manufactoring_year,
		  ],
		  (object) [
		    'key1' => 'Maker',
		    'value1' => $job->jobdetail->maker,
		    'key2' => 'Model/Variant',
		    'value2' => $job->jobdetail->model,
		  ],
		  (object) [
		    'key1' => 'Chassis No',
		    'value1' => $job->jobdetail->chassis_no,
		    'key2' => 'Engine No',
		    'value2' => $job->jobdetail->engine_no,
		  ],
		  (object) [
		    'key1' => 'RC Status',
		    'value1' => $job->jobdetail->rc_status == 0 ? 'Inactive' : 'Active',
		    'key2' => 'Seating Capacity',
		    'value2' => $job->jobdetail->seating_capacity,
		  ],
		  (object) [
		    'key1' => 'Issuing Authority',
		    'value1' => $job->jobdetail->issuing_authority,
		    'key2' => 'Fuel Type',
		    'value2' => $job->jobdetail->fuel_type,
		  ],
		  (object) [
		    'key1' => 'Colour',
		    'value1' => $job->jobdetail->color,
		    'key2' => 'Fitness Valid UpTo',
		    'value2' => date("d/m/Y",strtotime($job->jobdetail->fitness_valid_upto)),
		  ],
		  (object) [
		    'key1' => 'Laden Weight/Kg',
		    'value1' => $job->jobdetail->laden_weight,
		    'key2' => 'Unladen Weight/Kg',
		    'value2' => $job->jobdetail->unladen_weight,
		  ],
	);



	$techinicalKeyValue = array(
		  (object) [
		    'key1' => 'Engine & Transmission',
		    'value1' => $job->jobdetail->engine_transmission == 0 ? "Not In Running Condition" : "Running Condition",
		    'key2' => 'Electrical Gadgets',
		    'value2' =>  $job->jobdetail->electrical_gadgets == 0 ? "Not In Running Condition" : "Good & Operative Condition",
		  ],
		  (object) [
		    'key1' => 'Right Body',
		    'value1' => $job->jobdetail->right_side == 0 ? "Unsatisfactory" : "Satisfactory",
		    'key2' => 'Left Body',
		    'value2' =>  $job->jobdetail->left_body == 0 ? "Unsafe" : "Safe",
		  ],
		  (object) [
		    'key1' => 'Front Body',
		    'value1' =>  $job->jobdetail->front_body == 0 ? "Unsafe" : "Safe",
		    'key2' => 'Back Body',
		    'value2' => $job->jobdetail->back_body == 0 ? "Unsafe" : "Safe",
		  ],
		  (object) [
		    'key1' => 'Load Body',
		    'value1' =>  $job->jobdetail->load_body == 0 ? "Unsafe" : "Safe",
		    'key2' => 'All Glass Condition',
		    'value2' => $job->jobdetail->all_glass_condition == 0 ?"Unsafe" : "Safe",
		  ],
		  (object) [
		    'key1' => 'Cabin Condition',
		    'value1' =>  $job->jobdetail->cabin_condition == 0 ? "Unsatisfactory" : "Satisfactory",
		    'key2' => 'Head Lamps/Back Lamps',
		    'value2' =>  $job->jobdetail->head_lamp == 0 ? "Unsafe" : "Safe",
		  ],
		  (object) [
		    'key1' => 'Tyres Condition',
		    'value1' =>  $job->jobdetail->tyres_condition == 0 ? "Average" : "Satisfactory",
		    'key2' => 'Maintenance & Upkeep',
		    'value2' =>  $job->jobdetail->maintenance == 0 ? "Unsatisfactory" : "Satisfactory",
		  ],
		  (object) [
		    'key1' => 'Other Damages/Other Specify Remarks',
		    'value1' =>  $job->jobdetail->other_damages,
		    'key2' => '',
		    'value2' => '',
		  ]
	);


	//



?>

<!DOCTYPE html>
<html>
    <head>
        <title>
              Invoice generated by moval
        </title>

        <style>
#header,
#footer {
  position: fixed;
  left: 0;
	right: 0;
	color: #aaa;
	font-size: 0.9em;
}
#header {
  top: 0;
	border-bottom: 0.1pt solid #aaa;
}
#footer {
  bottom: -45;
  /*border-top: 0.1pt solid #aaa;*/
}
.seal{
	border-bottom: 0.1pt solid #aaa;
}
.page-number{
	float: right;
}

.page-number:before {
  content: "Page " counter(page)+1;
}
@page {
  header: page-header;
  footer: page-footer;
}
</style>
</head>

    <body style="font-size:16px;">

        <?php if(!$draft){ ?>
        <htmlpagefooter name="page-footer">
          <!-- <div style="margin-top:30px" class="page-number"></div> -->
          	
			  	<!-- <hr style="margin-top:1px;margin-bottom:1px;"> -->
			  	<div style="margin-bottom:2px;width:100%;display:flex;">

			  		<?php
          	if($footer_seal != ""){ 
          		?>
          		<div style="width:100%;margin-top:15px;">
						    <img style="width: 1200px;margin-bottom:5px;float: left;vertical-align: middle;height: 40px;" src="<?php  echo $footer_seal; ?>">
					  	</div> 
          	<?php 
          		}	
          	?>
          	
			  		<table style="border-collapse: collapse;margin-bottom:10px;margin-top:10px;width: 100%">
		    	 		<tr>
		    	 			<td style="text-align: left;width:33%;padding:<?php echo $paddingTableCell;?>">
		    	 					<p style="text-align:left;font-size:12px;margin-top:1px;margin-bottom:1px;">Veh. No.:<?php echo $regNo; ?></p>
		    	 			</td>
		    	 			<td  style="text-align: center;width:33%;padding:<?php echo $paddingTableCell;?>">
		    	 				<p style="width:100%;text-align:center;font-size:12px;margin-top:1px;margin-bottom:1px;">Insurance Anti Fraud Professional</p>
		    	 			</td>
		    	 			<td  style="text-align: right;width:33%;padding:<?php echo $paddingTableCell;?>">
		    	 				<p class="header-right" style="width:100%;font-size:12px;float:left;text-align:right;">Page {PAGENO}</p>
		    	 			</td>

		    	 		</tr>
		    	 	</table>

			  		
				  </div>
        </htmlpagefooter>
        <?php } ?>
		<!-- <div id="footer">
		  	<div style="margin-top:30px" class="page-number"></div>
			  <div class="seal" style="width: 100%;height:70px;border-bottom: 0.1pt solid #aaa;">
			  	<img style="float: left;vertical-align: middle;height: 50px;" src="<?php // echo $seal; ?>">
			  	<div style="margin-left: 15px;margin-top:15px" class="vehicle-name">Vehicle Number <?php // echo $regNo; ?></div>
			  </div>

		</div> -->


    <div class="container" style="width:100%;">
    	<?php if(!$draft){ ?>
    	 	<table  style="margin-top:2px;margin-bottom:2px;width:100%">
    	 		<tr>
		    	 	<td style="width:100%;text-align:center;">
		    	 		  <img style="vertical-align: middle;width: 1200px;" src="<?php echo $logoImage; ?>">
		    	 	</td>
		    	</tr>
		    </table>
    	 <?php } ?>



    	 <hr style="margin-top:2px;margin-bottom:2px;padding-top:2px;padding-bottom:2px;">

    	 <div class="inner-container">
    	 	<div class="header" style="width:100%;display:flex;">

    	 		<div class="header-left" style="width:50%;text-align:left;float:left;"><u>Ref No - <?php echo $refNo;?></u></div>


    	 		<div class="header-right" style="width:50%;float:left;text-align:right;"><u>Date - <?php echo $date;?></u></div>
    	 	</div>



				<table  style="margin-top:2px;margin-bottom:2px;width:100%">
    	 		<tr>
		    	 	<td style="width:30%">
		    	 			&nbsp;
		    	 	</td>
		    	 	<td style="width:40%">
		    	 		<table style="border-collapse: collapse;width:100%">
			    	 		<tr>
					    	 	<td  style="font-size: 15px;background-color: #dfeafd;text-align: center;width:100%;padding:<?php echo $paddingTableCellHalf;?>;border: 1px solid #000"><b><u>VEHICLE VALUATION REPORT</u></b><br>
			    	 			<b><u>TO WHOME IT MAY CONCERN</u></b></td>

					    	</tr>
					    </table>

		    	 	</td>
		    	 	<td style="width:5%">
		    	 			&nbsp;
		    	 	</td>
		    	 	<td style="width:25%;text-align:right;">

							  <img style="float: right;vertical-align: middle;width: 80px;" src="<?php echo $barcode; ?>">

		    	 	</td>
		    	</tr>
		    </table>










    	 	<!-- <div class="logo-heading" style="width:100%;margin-bottom:10px;margin-top:10px;height: 100px;">
    	 		<div class="other-content" style="width:900px;background-color: #dfeafd;text-align: center;margin:10px;border:1px solid;float: right;padding-left:40px;padding-right:40px;">
    	 			<b><u>VEHICLE VALUATION REPORT</u></b><br>
    	 			<b><u>TO WHOME IT MAY CONCERN</u></b>
    	 		</div>
    	 	</div> -->


    	 	<table style="border-collapse: collapse;margin-bottom:10px;margin-top:10px;width: 100%;border: 1px solid #000;">
    	 		<tr>
    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000">Report Requested by</td>
    	 			<td colspan="3" style="width:75%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $job->client->name.', '.$username;?></td>
    	 		</tr>

    	 		<tr>
    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000">Inspection Date/Time</td>
    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo date("d/m/Y",strtotime($inspectionDateTime));?></td>
    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000">Inspection Place</td>
    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $inspectionPlace
    	 			;?></td>
    	 		</tr>

    	 		<tr>
    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000;font-size: 25px;"><b><span style="font-family: DejaVu Sans; sans-serif;">&#8377;</span></b></td>
    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $amount;?></td>
    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000">Amount in Word</td>
    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $amountInWords
    	 			;?></td>
    	 		</tr>











    	 	</table>

    	 	<!-- other details table -->

    	 	<?php /*
    	 	<table style="border-collapse: collapse;margin-top:10px;width: 100%;">
    	 		<tr>
    	 			<td  style="height: 120px;">
    	 				<table style="border-collapse: collapse;width: 100%;height: 100px;">
    	 					<tr>
	    	 					<td style="height: 50px;width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000">Vehicle Owner Name</td>
			    	 			<td style="height: 50px;width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $vehicelOwnerName;?></td>
			    	 		</tr>
			    	 		<tr>
			    	 			<td style="height: 50px;width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000">Registation No</td>

			    	 			<td style="height: 50px;width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $regNo;?></td>
    	 					</tr>
    	 				</table>
    	 			</td>


    	 			<td colspan="2" style="height: 120px;">
    	 				<table style="border-collapse: collapse;width: 100%;height: 120px;">
    	 					<tr>
	    	 					<td style="height: 120px;width:50%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000">Vehicle Owner Address</td>
			    	 			<td style="height: 120px;width:50%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $address;?></td>

    	 					</tr>
    	 				</table>
    	 			</td>
    	 		</tr>
    	 	</table>
    	*/  ?>

    	 	<table style="border-collapse: collapse;margin-top: -2px;margin-bottom:10px;width: 100%;border: 1px solid #000;">


    	 			<tr>
    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000">Vehicle Owner Name</td>

    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $vehicelOwnerName;?></td>
    	 			<td rowspan="2" style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000">Vehicle Owner Address</td>
    	 			<td rowspan="2" style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $address;?></td>
    	 		</tr>


    	 		<tr>
    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000">Registration No</td>
    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $regNo;?></td>
    	 		</tr>



    	 		<?php
    	 			foreach ($additionalKeyValue as $obj){ ?>

    	 				<tr>
		    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $obj->key1;?></td>
		    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $obj->value1;?></td>

		    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $obj->key2;?></td>
		    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $obj->value2;?></td>
		    	 		</tr>


    	 		<?php	}
    	 		?>



    	 	</table>


    	 	<table style="border-collapse: collapse;margin-top:10px;width: 100%;">
    	 		<tr>
		    	 	<td colspan="4" style="background-color: #dfeafd;text-align: center;width:100%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><b style="text-transform: uppercase;">Technical Features/Damages</b></td>

		    	</tr>
    	 		<?php
    	 			foreach ($techinicalKeyValue as $obj){

    	 				if($obj->key1 == "Other Damages/Other Specify Remarks"){ ?>

    	 				<tr>
		    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $obj->key1;?></td>
		    	 			<td colspan="3" style="width:75%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $obj->value1;?></td>
		    	 		</tr>

    	 				<?php }else{ ?>



    	 				<tr>
		    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $obj->key1;?></td>
		    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $obj->value1;?></td>

		    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $obj->key2;?></td>
		    	 			<td style="width:25%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $obj->value2;?></td>
		    	 		</tr>

		    	 		<?php } ?>
    	 		<?php	}
    	 		?>


    	 	</table>



    	 	



    	 	<table style="border-collapse: collapse;width: 100%;text-align:center;margin-top:10px">


	        <tr>
		     		<td  style="width:50%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><img style="width:100%;height:<?php echo $height;?>;" height="100px" src="<?php echo $frontImage;?>"/></td>
		     		<td  style="width:50%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><img style="width:100%;height:<?php echo $height;?>;" height="100px" src="<?php echo $backImage;?>"/></td>
	        </tr>

	        <tr>
		     		<td  style="width:50%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><img style="width:100%;height:<?php echo $height;?>;" height="100px" src="<?php echo $leftImage;?>"/></td>
		     		<td  style="width:50%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><img style="width:100%;height:<?php echo $height;?>;" height="100px" src="<?php echo $rightImage;?>"/></td>
	        </tr>

    	 	</table>



    	 	<table style="border-collapse: collapse;margin-top:325px;width: 100%;text-align:center">
    	 		<tr>
		    	 	<td style="background-color: #dfeafd;text-align: center;width:100%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000;"><b style="text-transform: uppercase;">CHASSIS NO</b></td>

		    	</tr>
		    </table>

		    <table style="border-collapse: collapse;width: 100%;text-align:center;">
    	 		<tr>
		     		<td  colspan="2" style="width:100%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000;"><img style="height:<?php echo $height_horizontal;?>;width:100%;"  src="<?php echo $chassisImage;?>"/>
		     		</td>
	        </tr>
	      </table>


	      	<table style="border-collapse: collapse;width: 100%;text-align:center;margin-top:10px">
    	 		<tr>
		     		<td  colspan="2" style="width:100%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000;"><img style="height:<?php echo $height_horizontal;?>;width:100%;"  src="<?php echo $odometerImage;?>"/>
		     		</td>
	        </tr>
	      </table>









    	 	<?php if(sizeof($job->other_images)){ ?>
    	 		<table style="border-collapse: collapse;margin-top:10px;width: 100%;text-align:center">
	    	 		<tr>
			    	 	<td colspan="2" style="background-color: #dfeafd;text-align: center;width:100%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><b>Other</b></td>
			    	</tr>
		  		</table>
		  		<table style="border-collapse: collapse;margin-top:10px;width: 100%;text-align:center">

		  				<?php
		  				$j = 0;
		  				$k = 0;
		  				$arr_other_images = $job->other_images;
		  				foreach ($job->other_images as $imgObjOther){

		  				?>
		  				<tr>
		  			 		<td  style="width:50%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><img style="height:<?php echo $height;?>;" height="100px" src="<?php echo config('app.imageurl')."".$arr_other_images[$k]->name;?>"/></td>
		  			 	<?php $k++;?>
		  			 		<td  style="width:50%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><img style="height:<?php echo $height;?>;" height="100px" src="<?php echo config('app.imageurl')."".$arr_other_images[$k]->name;?>"/></td>

				    	</tr>
	        		<?php

	        		$j++;
	        		$j++;
	        		$k++;
	        		if($j >= count($arr_other_images)-1){
	        			break;
	        		}
	        		}

	        		if((count($arr_other_images)) % 2 != 0){ ?>

	        			<tr>
		  			 		<td  style="width:50%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><img style="height:<?php echo $height;?>;" height="100px" src="<?php echo config('app.imageurl')."".$arr_other_images[(count($arr_other_images)-1)]->name;?>"/></td>
		  			 	<?php $k++;?>
		  			 		<td  style="width:50%;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000">&nbsp;</td>

				    	</tr>

	        		<?php }
	        		?>



		  	</table>





    	 	<?php }?>

    	 	<?php if(!$draft){ ?>
    	 	<table style="border-collapse: collapse;margin-bottom:10px;margin-top:10px;width: 100%;border: 1px solid #000;">
    	 		<tr>
    	 			<td style="font-size:12px;padding:<?php echo $paddingTableCell;?>;border: 1px solid #000"><?php echo $approveText;?></td>
    	 		</tr>
    	 	</table>


    	 	<p style="font-size:12px;margin-top:20px">Approved By </p>

    	 	<div class="" style="float:left;width:100%;margin-top:2px">
		  	   <img style="float: left;vertical-align: middle;height: 80px;" src="<?php  echo $seal; ?>">
		  	</div>
		  	<br>
    	 	
    	 	<p style="font-size:12px;margin-top:5px"><?php echo $job->authorized_person_name;?> </p>
    	 	<p style="font-size:12px;margin-top:5px"><?php echo $job->designation;?> </p>

    	 	<?php }?>
    	 </div>




    	</div>



    </body>
</html>
